language: node_js
node_js:
  - "stable"
  - "10"
  - "9"
  - "8"
before_script:
  - export CI=true
install:
  - npm -g i yarn
  - yarn install
script:
  - yarn test
after_success:
  - yarn run coverage:server
